### ISSUE TITLE
Dependabot Extension In Azure Devops Pipeline is failing

### ISSUE THREAD

**Issue by prajwalkumar9** [tinglesoftware/dependabot-azure-devops#1064] opened 2024-04-02 04:44 UTC
We are currently using the dependabot extension in azure devops pipeline to automatically upgrade packages.

![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/106602044/2568c426-c0b4-4e3b-bde8-6ea6a3d5e9d6)

This is the error we see in pipeline when we run the dependabot stage.

/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11319/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'requirements_update_strategy': Expected type T.nilable(Dependabot::RequirementsUpdateStrategy), got type Symbol with value :bump_versions (TypeError)
Caller: /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11319/lib/types/private/methods/call_validation.rb:215

Currently we are using the following dependabot extension

![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/106602044/4d4037bb-9e7f-4bc5-bbc4-a5988e1a927f)

**Comment by rich-sykes** [comment] 2024-04-02 08:50
I am experiencing exactly the same issue since 19th March.


`Checking if azure-storage-blob 12.19.1 needs updating
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11319/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'requirements_update_strategy': Expected type T.nilable(Dependabot::RequirementsUpdateStrategy), got type Symbol with value :bump_versions_if_necessary (TypeError)


Caller: /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11319/lib/types/private/methods/call_validation.rb:215


Definition: /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.249.0/lib/dependabot/update_checkers/base.rb:62
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11319/lib/types/configuration.rb:303:in `call_validation_error_handler'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11319/lib/types/private/methods/call_validation.rb:300:in `report_error'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11319/lib/types/private/methods/call_validation.rb:218:in `block in validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11319/lib/types/private/methods/signature.rb:234:in `block in each_args_value_type'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11319/lib/types/private/methods/signature.rb:228:in `each'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11319/lib/types/private/methods/signature.rb:228:in `each_args_value_type'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11319/lib/types/private/methods/call_validation.rb:215:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11319/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from bin/update_script.rb:339:in `new'
	from bin/update_script.rb:339:in `update_checker_for'
	from bin/update_script.rb:559:in `block in <main>'
	from bin/update_script.rb:545:in `each'
	from bin/update_script.rb:545:in `<main>'
`

**Comment by catsburg** [comment] 2024-04-05 14:21
I believe this is the same issue as #1046

**Comment by mburumaxwell** [comment] 2024-06-08 12:14
Duplicate of #1046

**Closed by mburumaxwell** 2024-06-08 12:14 UTC
