### ISSUE TITLE
Pull Requests are created for ignored dependencies as well

### ISSUE THREAD

**Issue by mrdrdocs** [tinglesoftware/dependabot-azure-devops#460] opened 2023-01-09 22:27 UTC
We have onboarded dependabot to one of the Repos and ignored a couple of packages so not to look for updates. Still, Pull Requests are created to ignore dependencies @dependabot. 

**Configuration:**
<ins>.github/dependabot.yml</ins>

version: 2
registries:
   nuget-org:
     type: nuget-feed
     url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: "nuget"
    directory: "/" #root
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "Polly"
      - dependency-name: "Polly.*"
      - dependency-name: "Moq"
      - dependency-name: "FluentAssertions"
    
We see PRs are created for Polly, Moq, FluentAssertions and Polly.* [ Polly.Extensions.Http ].
Please provide inputs on this to fix the issue!

**Comment by mburumaxwell** [comment] 2023-01-11 11:45
Please provide a public Azure DevOps repository for reproduction of this issue!

**Comment by mrdrdocs** [comment] 2023-01-14 16:21
we will work for Microsoft. Due to the privacy restrictions, I can't provide the repo information. I can answer for more questions if required. we followed configuration ignore options from [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore). Everything is working fine but only concern is, The pull requests are created even for ignored dependencies as well.

**Comment by mburumaxwell** [comment] 2023-01-16 14:41
Isn't it really strange that Microsoft, the maker/owner of Azure DevOps cannot create a repro due to privacy concerns? Does it mean you don't trust your own Azure DevOps? Generally a repro is not a clone of your current repository but instead a simplified, fairly trivial representation of the issue. In this case, just the project files with the necessary files.

Anyway, I took the liberty to see if there is a new issue that we are not seeing in our own internal usage. Just like #399 , the ignore section works, unless you are using different versions for the task and docker container or are using older task versions.

The repository: https://dev.azure.com/tingle/dependabot/_git/repro-460
The pipeline: https://dev.azure.com/tingle/dependabot/_build/results?buildId=54447

Did I miss anything?

**Comment by mrdrdocs** [comment] 2023-01-17 03:56
Hi @mburumaxwell,
Thanks for the response.
The dependabot.yml is exactly same except registries section.

dependabot.yml
-----------------
version: 2
registries:
  nuget-org:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: "nuget"
    directory: "/" #root
    schedule:
      interval: "daily"
    ignore:
       - dependency-name: "Polly"
       - dependency-name: "Polly.*"
       - dependency-name: "Moq"
       - dependency-name: "FluentAssertions"
  
and azure-pipelines.yml contains the below piece of code.

azure-pipelines.yml
----------------------
trigger: none # Disable CI trigger
schedules:
- cron: '0 2 * * MON' # Monday at 2am UTC
  always: true # run even when there are no code changes
  branches:
    include:
      - 'main'
  batch: true
  displayName: Daily
pool:
  vmImage: 'ubuntu-latest' # requires macos or ubuntu (windows is not supported)
variables:
- group: Dependabot
steps:
- task: NuGetAuthenticate@1
  displayName: 'NuGet Private Feed Authentication'
- task: dependabot@1
  inputs:
    useConfigFile: true
    
   Please comment If I need to provide any further information.

**Comment by mburumaxwell** [comment] 2023-01-17 03:58
What is the NuGetAuthenticate@1 task meant to do in this particular case?

Are you using one private feed with one ore more upstream sources?

Why is the nuget feed added to the registries of the configuration file?

**Comment by mrdrdocs** [comment] 2023-01-17 04:02
Yes @mburumaxwell  
1. the nuget feed will authenticate the upstream sources
2. We have two registries
3.  Added two registries. One is nuget and the other one is own upstream source

**Comment by mburumaxwell** [comment] 2023-01-17 04:16
For dependabot, things work a bit differently. If you have custom/private feeds you need to add a nuget.config file to the repository in the same directory as the one in the configuration. That's where you add nuget.org if you still use it. Otherwise just add the feeds you use there. In the configuration file you will then provide credentials for each feed that is private.

Sample configuration file at `.github/dependabot.yml`:

```yml
version: 2
updates:
- package-ecosystem: "nuget" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "daily"
    time: "02:00"
  open-pull-requests-limit: 10
registries:
  contoso:
    type: nuget-feed
    url: '<feed-url>' # e.g. an organization-wide feed URL will look like https://pkgs.dev.azure.com/<org-name>/_packaging/<feed-name>/nuget/v3/index.json
    token: ':${{DEFAULT_TOKEN}}'
```

Example nuget.config file at `nuget.config`:

```yml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear /> <!-- ensure only the sources defined below are used -->
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="contoso" value="https://pkgs.dev.azure.com/contoso/_packaging/Alice/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

Example pipeline file:

```yml
steps:
- task: dependabot@1
  inputs:
    useConfigurationFile: true
    azureDevOpsAccessToken: $(DEFAULT_TOKEN)
```

Remember to add DEFAULT_TOKEN to the pipeline variables with a PAT that has the following permissions:
- Packaging (Read)
- Code (Full)
- Pull Requests Threads (Read & Write)

The owner of the PAT must also be added to permissions of the specific feeds either directly or via a group and with at least reader permissions.

> Note that the above are examples that need to be tuned to your specific scenario.

**Comment by mrdrdocs** [comment] 2023-01-17 04:26
Yes @mburumaxwell 
dependabot@1 task have the below additional properties defined.

azure-pipelines.yml
---------------------
- task: dependabot@1
  inputs:
    useConfigFile: true
    azureDevOpsAccessToken: '$(System.AccessToken)'
    gitHubAccessToken: '$(GitHubAccessToken)'
    extraEnvironmentVariables: DEPENDABOT_EXTRA_CREDENTIALS=[{"type":"nuget_feed","token":"$(VSS_NUGET_ACCESSTOKEN)","url":"<feed-url>"}]
   
 and nuget.config is same as you defined.

**Comment by mburumaxwell** [comment] 2023-01-17 04:28
Okay. Now at this time I can only help with a reproduction because clearly there's something else missing.
You can share it directly to me via mburumaxwell at tingle dot software

**Comment by mrdrdocs** [comment] 2023-01-17 04:30
Okay @mburumaxwell  do you want me to share the files?

**Comment by mburumaxwell** [comment] 2023-01-17 04:32
Access to a sample repository will help. You can strip down all the super sensitive stuff but keep what is necessary to reproduce the issue.

**Comment by mrdrdocs** [comment] 2023-01-17 04:35
Is it possible to get the access on the repo you created. So, I will create my branch and add the required files to repro ( or ) need to create a new Azure DevOps account with a new repo?

**Comment by mburumaxwell** [comment] 2023-01-17 04:37
Easiest and fastest way to get this done is to create a new AzureDevOps organization even with you personal account. Add the files there then share with me or invite me to collaborate.

**Comment by mrdrdocs** [comment] 2023-01-17 04:56
Sure @mburumaxwell  I will try to repro and drop you the link by tomorrow EOD.

**Comment by mburumaxwell** [comment] 2023-01-17 14:15
Ok

**Comment by mrdrdocs** [comment] 2023-01-17 16:02
Hi @mburumaxwell  Created a new repo and committed all the required files to repro the issue. Seen an issue to run the pipelines **"No hosted parallelism has been purchased or granted. To request a free parallelism grant"** and dropped an request for **Azure DevOps Parallelism Request** Please let me know the alias to invite you to the organization.

**Comment by mburumaxwell** [comment] 2023-01-17 17:19
I'm not sure I understand the parallelism issue.
Email: mburumaxwell at tingle dot software

**Comment by mrdrdocs** [comment] 2023-01-17 21:54
Invited to the Repo @mburumaxwell . You can find the issue from pipelines!

**Comment by mburumaxwell** [comment] 2023-01-18 04:29
I have not received any invite yet.

**Comment by mrdrdocs** [comment] 2023-01-18 17:13
I dropped invite on mburumaxwell@tinglesoftware

**Comment by mburumaxwell** [comment] 2023-01-18 20:43
Still haven't received. You missed a dot somewhere in the domain.

**Comment by mrdrdocs** [comment] 2023-01-18 20:49
Can you please drop me exact alias to invite you in @mburumaxwell

**Comment by mburumaxwell** [comment] 2023-01-18 20:54
I'm not too conversant with cross-organization invites but according to this [link](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/add-external-user?view=azure-devops), you will only need the email address that I shared earlier.

**Comment by mrdrdocs** [comment] 2023-01-23 21:53
invited you again @mburumaxwell with the address "**mburumaxwell@tingle.software**"

**Comment by mburumaxwell** [comment] 2023-01-24 03:03
> Is it possible to connect over teams channel @mburumaxwell I will schedule a call and discuss on the issue based on your availability

Sure, you can send and invite to the same email.

**Comment by mrdrdocs** [comment] 2023-01-24 20:19
Hi @mburumaxwell  Scheduled a team's meeting to discuss on the dependabot ignore issue! Please confirm or reschedule based on your availability!

**Comment by mburumaxwell** [comment] 2023-01-25 05:20
I have seen the scheduled meeting. I work in a different timezone GMT+[0-3] is most ideal so I will reschedule.

**Comment by mrdrdocs** [comment] 2023-01-25 06:02
Sure @mburumaxwell  Please reschedule based on your availability!

**Comment by mburumaxwell** [comment] 2023-02-07 14:41
Closing, conversation moved elsewhere.

**Closed by mburumaxwell** 2023-02-07 14:41 UTC
