### ISSUE TITLE
Azure YAML pipeline - dependabot on Node/Express project

### ISSUE THREAD

**Issue by samiujan** [tinglesoftware/dependabot-azure-devops#187] opened 2021-09-28 09:12 UTC
Hi

I am trying to run dependabot on a node/express project's package.json but I get the following error - I am assuming setting up and using dependabot is much more involved?

```

098f233eb6e8: Pull complete
ca3bb4b243af: Pull complete
d1d1f5dd4288: Pull complete
2527b2d06b57: Pull complete
35dae2e8b0e6: Pull complete
Digest: sha256:23b22c05e299afc1432ee09ec533a752d03003aa97b8f77cfe066661899e25be
Status: Downloaded newer image for tingle/dependabot-azure-devops:0.5
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.4-compliant syntax, but you are running 2.7.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:111:in `rescue in fetch_file_if_present': Dependabot::DependencyFileNotFound (Dependabot::DependencyFileNotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:90:in `fetch_file_if_present'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.162.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:55:in `package_lock'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.162.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:37:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./update-script.rb:245:in `<main>'
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/clients/azure.rb:237:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/clients/azure.rb:93:in `fetch_repo_contents_treeroot'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/clients/azure.rb:69:in `fetch_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:309:in `_azure_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:208:in `_fetch_repo_contents_fully_specified'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:179:in `_fetch_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:163:in `repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:103:in `fetch_file_if_present'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.162.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:55:in `package_lock'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.162.1/lib/dependabot/npm_and_yarn/file_fetcher.rb:37:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.162.1/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./update-script.rb:245:in `<main>'
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using 'https://dev.azure.com:443/' as API endpoint
Fetching npm_and_yarn dependency files for company/project/_git/repo
Targeting 'dev' branch under './' directory
Using 'bump_versions' requirements update strategy
##[error]The process '/usr/bin/docker' failed with exit code 1
Finishing: dependabot

```

My PAT has set permissions for:
```

- Code (Full)
- Pull Requests Threads (Read & Write).
``` 

The following is my YAML file:

```
trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:
   - task: dependabot@1
     inputs:
        packageManager: 'npm'
        directory: './'
        targetBranch: 'dev'
        versioningStrategy: 'auto'
        azureDevOpsAccessToken: '<PAT here>'
        targetRepositoryName: '<repo name here>'
```

**Comment by mburumaxwell** [comment] 2022-01-19 09:20
Hi @samiujan , as pointed out by @MO2k4 , the issue is whether the dependency file (`package.json` for npm) is located. You can fix this by specifying the `directory` input to the correct path e.g. `/` for root or `/frontend` if you package.json file is located at `frontend/package.json`.

I will proceed and close the issue. Reopen if needed.

**Closed by mburumaxwell** 2022-01-19 09:20 UTC
Labels: question, javascript
