### ISSUE TITLE
Abandoning PRs does not work as expected with multiple updates in one repository

### ISSUE THREAD

**Issue by ko16a46** [tinglesoftware/dependabot-azure-devops#451] opened 2022-12-23 19:32 UTC
Hello!

I like the new 'Abandon outdated PRs' feature but it seems like it doesn't work well with monorepos that have multiple projects to update. 

We notice that dependabot will create a PR to update a dependency in one project on our repo, but then immediately abandon it when it goes to the next package in the repo. Right now there are zero updates from dependabot. We don't observe this behavior in repos that contain only one project to update.

### Additional Information
- The affected repo contains multiple Dart / Flutter packages. We are using the `pub` package ecosystem in Dependabot.
- We are using Dependabot for Azure Devops version 1.13.378
- Our monorepo also has no lock files included in source control, could this actually be the issue?

**Comment by mburumaxwell** [comment] 2022-12-24 02:36
Thank you for reporting this. Indeed working in a mono repo wasn't considered, especially for different ecosystems or different directories.
An attempt to fix this was made in #447 but clearly there's more scenarios. You can opt out using the new input in #448.

I will keep this issue open as other alternatives are looked into. Maybe other similar reports will provide more insight. Could even be a contribution.

**Comment by davesmits** [comment] 2023-01-18 12:41
Some problem here.. Have a repo that contains a .net project and a anuglar app. PR's get created and directly Abandoned

**Comment by mburumaxwell** [comment] 2023-01-18 12:55
This currently only works with repositories with only one update entry in the configuration file which means it is very good for repositories with just NuGet and all projects are handled in the root.

Unfortunately, I have not found a way to fix this without storing pull requests created per update in each repository.

I recommend not enabling this feature but otherwise contributions are welcome.

**Comment by davesmits** [comment] 2023-01-18 12:56
PR's get a tag for which ecosystem they are. would that be a good way to match them? 
<img width="515" alt="image" src="https://user-images.githubusercontent.com/3148438/213177294-24dfdebc-550b-4f8c-8b49-e2e939cd0896.png">

**Comment by mburumaxwell** [comment] 2023-01-18 13:08
> PR's get a tag for which ecosystem they are. would that be a good way to match them?
> <img alt="image" width="515" src="https://user-images.githubusercontent.com/3148438/213177294-24dfdebc-550b-4f8c-8b49-e2e939cd0896.png">

Labels can be altered in the configuration file. Further, what happens to two updates of the same ecosystem? Maybe the title like we do when closing existing PRs?

**Comment by mburumaxwell** [comment] 2023-01-24 03:19
> I created a public DevOps project with NPM and Docker to reproduce the error.
> 
> ```yaml
> version: 2
> updates:
>   - package-ecosystem: npm
>     directory: /
>     schedule:
>       interval: weekly
>   - package-ecosystem: docker
>     directory: /docker/
>     schedule:
>       interval: weekly
> ```
> 
> [Build Log](https://dev.azure.com/dependabot-debug/npm-docker/_build/results?buildId=18&view=logs&j=be2c39d2-39df-5cd1-ffd9-71ea239221a0&t=5f55c3fc-e1c5-50e2-fd1d-401b45cd1abb&l=328)
> 
> PR is being created and closed shortly after
> 
> [Pull Request](https://dev.azure.com/dependabot-debug/npm-docker/_git/npm-docker/pullrequest/4)

Thanks for offering this repro. Somehow I believed this was disabled by default but I was wrong. In #482, it is now disabled by default.

**Comment by gitolicious** [comment] 2023-01-24 07:28
Alright, thank you. I can confirm the new default value was used in 0.14.1: [Build Log](https://dev.azure.com/dependabot-debug/npm-docker/_build/results?buildId=19&view=logs&j=be2c39d2-39df-5cd1-ffd9-71ea239221a0&t=5f55c3fc-e1c5-50e2-fd1d-401b45cd1abb&l=326)
After enabling it explicitly
```yaml
        abandonUnwantedPullRequests: true
```
we are back (as expected) to the wrong behavior of abandoning PRs right after creation: [Build Log](https://dev.azure.com/dependabot-debug/npm-docker/_build/results?buildId=20&view=logs&j=be2c39d2-39df-5cd1-ffd9-71ea239221a0&t=5f55c3fc-e1c5-50e2-fd1d-401b45cd1abb&l=315)

**Comment by mburumaxwell** [comment] 2023-01-24 07:39
@gitolicious Kindly do not use that feature when your update configuration has multiple updates.

**Comment by gitolicious** [comment] 2023-01-24 08:17
Sure, that's understood. Just wanted to make it explicitly clear for everyone. The title of this issue is just mentioning "monorepos" which first let me thinking this doesn't affect me, though it is a problem whenever you have multiple `updates` in your `dependabot.yml`.

One messy workaround for users who urgently need a fix could be having one `dependabot.yml` each, which you then copy around to `.github/` with shell scripts in between dependabot tasks. For me though, I simply disabled Docker checks in my project.

**Comment by gitolicious** [comment] 2023-01-24 08:42
Btw, the `targetUpdateIds` function (#478 released in 0.14.1) also doesn't help:

```yaml
    - task: dependabot@1
      inputs:
        abandonUnwantedPullRequests: true
        targetUpdateIds: '0'
    - task: dependabot@1
      inputs:
        abandonUnwantedPullRequests: true
        targetUpdateIds: '1'
```
[Build Log](https://dev.azure.com/dependabot-debug/npm-docker/_build/results?buildId=21&view=logs&j=be2c39d2-39df-5cd1-ffd9-71ea239221a0&t=7a8fa0dc-03d6-5c12-6bb8-b1e1d318b5c0&l=49)

**Comment by mburumaxwell** [comment] 2023-01-24 08:54
#478 was only meant to solve #466 not this one. There's still no viable fix or workaround for closing unwanted PRs when there are multiple updates in the same repository. Contributions are welcome.

As regards the title, you have a valid concern. Thanks for raising it, I will update.

**Comment by lucasfijen** [comment] 2024-05-06 09:41
We are also running into this issue, with newer versions of a package leaving dangling branches/PR's of earlier PRs that arent autoclosed, wich we cant remove due to our branch policies.

I was wondering, would it be possible to make use of the branch names to get a work around on this?
When having a pip and docker package ecosystem, the branches will look like:
- dependabot/docker/agent/ubuntu-24.04)
- dependabot/pip/json-version here

The pip step would only have to close the */pip/* branches,
whereas the dockeer part should only autoclose */docker/* branches.

I'm not into this code, so not aware of the limitations in the solution space, but logic like this would fix all our usecases.

**Comment by mburumaxwell** [comment] 2024-07-20 03:48
This is likely fixed in https://github.com/tinglesoftware/dependabot-azure-devops/pull/1221

**Comment by rhyskoedijk** [comment] 2024-07-20 04:41
I wasn't able to test this exact scenario without knowing OP's `dependabot.yml` config; However, these scearios _should_ be supported now so long as you **don't define multiple of the same package ecosystems**.

Previously you had to do this because Dependabot only supported a single directory, but now with [multiple directory support](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories), duplicating ecosystems can [mostly*] be avoided except.

### For monorepo or multi-directory projects

#### Do this:
```yml
version: 2
updates:
  - package-ecosystem: "pub"
    directories:
      - "/src/app1"
      - "/src/app2"
      - "/src/lib1"
```

#### Avoid this, it will cause the PR abandonment issue:
```yml
version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/src/app1"
  - package-ecosystem: "pub"
    directory: "/src/app2"
  - package-ecosystem: "pub"
    directory: "/src/lib1"
```

### For multi-package ecosystem projects

#### Do this:
```yml
updates:
  - package-ecosystem: "npm"
    directory: "/"
  - package-ecosystem: "docker"
    directory: "/docker"
  - package-ecosystem: "pub"
    directories:
      - "/src/app1"
      - "/src/app2"
      - "/src/lib1"
```

* If you absolutely require two different configs for the same package ecosystem, this issue will still happen. Support for it could be added, but I am not sure if it is even a valid use case now that multiple directories are supported.

**Closed** 2024-08-24 09:15 UTC
Labels: bug, help wanted
