### ISSUE TITLE
Ruby type errors (includes Sorbet)

### ISSUE THREAD

**Issue by andybakerbrfc** [tinglesoftware/dependabot-azure-devops#999] opened 2024-02-19 12:03 UTC
**Describe the bug**
Failure to update with error message:

> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'credentials': Expected type T.nilable(Dependabot::Credential), got type Hash with value {"type"=>"git_source", "hos..."} (TypeError)

This is when fetching source from git using the token defined on line 142 of update_script.rb. This was on a script working prior to 1.26.2. The setup we use is simply:

```
trigger: none
variables:
  - group: "Dependabot"
schedules:
  - cron: "0 5 * * *"
    always: true
    branches:
      include:
        - main
    batch: true
    displayName: Daily
pool:
  vmImage: "ubuntu-latest"
steps:
  - task: npmAuthenticate@0
    inputs:
      workingFile: ".npmrc"
  - task: dependabot@1
    env:
      DEPENDABOT_PAT: $(common-feed-token)
```

I do not know ruby, but if I were to guess I say that the structure being created on line 142 no longer passes the type checking.

**To Reproduce**
1. Run the above pipeline on Azure on version 1.26.2

**Expected behavior**
The script to execute as before.

**Extension (please complete the following information):**
 - Host: Azure DevOps
 - Version 1.26.2

**Additional Info**
> Agent name: 'Hosted Agent'
> Current agent version: '3.234.0'
> Current image version: '20240212.1.0'
> Downloading task: npmAuthenticate (0.231.0)
> Downloading task: dependabot (1.26.659)

**Comment by andybakerbrfc** [comment] 2024-02-19 12:07
The complete stack trace:
```
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'credentials': Expected type T.nilable(Dependabot::Credential), got type Hash with value {"type"=>"git_source", "hos...XjHLWjwXgMCib4TN8eFOE632dzYg"} (TypeError)
Caller: /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/clients/azure.rb:44
Definition: /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/clients/azure.rb:59
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/configuration.rb:303:in `call_validation_error_handler'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:300:in `report_error'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:218:in `block in validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/signature.rb:213:in `each_args_value_type'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:215:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/clients/azure.rb:44:in `new'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/clients/azure.rb:44:in `for_source'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from bin/update_script.rb:529:in `<main>'
```

**Comment by mohitvashistha** [comment] 2024-02-19 12:17
`/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'credentials': Expected type T.nilable(Dependabot::Credential), got type Hash with value {"type"=>"git_source", "hos..._lpyrJtruk4_Xn9kZMiKAV3ujYZw"} (TypeError)
Caller: /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/clients/azure.rb:44
Definition: /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/clients/azure.rb:59
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/configuration.rb:303:in `call_validation_error_handler'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:300:in `report_error'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:218:in `block in validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/signature.rb:213:in `each_args_value_type'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:215:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/clients/azure.rb:44:in `new'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/clients/azure.rb:44:in `for_source'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from bin/update_script.rb:529:in `<main>'
##[error]The process '/usr/bin/docker' failed with exit code 1
Finishing: dependabot
`

**Comment by AnujRajoriya** [comment] 2024-02-19 12:34
I am also going through with the similar issue.

**Comment by mburumaxwell** [comment] 2024-02-19 13:14
This should be fixed in https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/1.26.3

@andybakerbrfc, if this is fixed kindly close. Also, the `npmAuthenticate@0` is unnecessary.

**Comment by andybakerbrfc** [comment] 2024-02-19 13:16
Will test and get back to you 👍.

**Comment by andybakerbrfc** [comment] 2024-02-19 13:21
Almost.

There is another type error:
```
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'milestone': Expected type T.nilable(T.any(Integer, T::Array[String])), got type String with value "69040" (TypeError)
Caller: /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:215
Definition: /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/pull_request_creator.rb:175
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/configuration.rb:303:in `call_validation_error_handler'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:300:in `report_error'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:218:in `block in validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/signature.rb:234:in `block in each_args_value_type'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/signature.rb:228:in `each'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/signature.rb:228:in `each_args_value_type'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:215:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from bin/update_script.rb:810:in `new'
	from bin/update_script.rb:810:in `block in <main>'
	from bin/update_script.rb:549:in `each'
	from bin/update_script.rb:549:in `<main>'
```

Close this and create another bug or do you want to treat this as an a continuation?

**Comment by mohitvashistha** [comment] 2024-02-19 13:31
It ran but failed to create PR:
```

Package [xxxxx.Diagrams.Core] Does not exist as a dependency in [/home/dependabot/dependabot-updater/tmp/xxxxx/CG_APP/_git/CG_APP/Sources/xxxxx.xxxxx.CAD/xxxxx.xxxxx.CAD.csproj].
Update complete.
Submitting xxxxx.Diagrams.Core pull request for creation.
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/_types.rb:222:in `must': Passed `nil` into T.must (TypeError)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/pull_request_creator/branch_namer/solo_strategy.rb:49:in `prefixes'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/pull_request_creator/branch_namer/solo_strategy.rb:39:in `new_branch_name'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/pull_request_creator/branch_namer.rb:68:in `new_branch_name'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/pull_request_creator.rb:306:in `azure_creator'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/pull_request_creator.rb:236:in `create'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from bin/update_script.rb:833:in `block in <main>'
	from bin/update_script.rb:549:in `each'
	from bin/update_script.rb:549:in `<main>'
##[debug]Exit code 1 received from tool '/usr/bin/docker'
##[debug]STDIO streams have closed for tool '/usr/bin/docker'
##[debug]task result: Failed
##[error]The process '/usr/bin/docker' failed with exit code 1
##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;]The process '/usr/bin/docker' failed with exit code 1
##[debug]Processed: ##vso[task.complete result=Failed;]The process '/usr/bin/docker' failed with exit code 1

```

**Comment by mburumaxwell** [comment] 2024-02-19 14:14
Since I have no clue how to get a hold of all these issues yet and seeing the upstream repository is migrating procedurally, let's keep this issue open until we have resolved all type/sorbet-related issues.

The error from creating a PR has been fixed (`UpdateChecker` was forgotten). The others related to credentials will hopefully be fixed by #1000 . For `milestone`, it should be fixed with #1001 These should now be deployed in your environment(s) so you can test. Kindly report back.

**Comment by andybakerbrfc** [comment] 2024-02-19 14:34
All working for me now. Many thanks for reacting so fast.

**Comment by mburumaxwell** [comment] 2024-02-19 16:01
Great!

Keeping this open for a week which should cover most people.

**Comment by johannes-cogitaris** [comment] 2024-02-20 15:24
I'm getting this error:
```bash
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/clients/azure.rb:388:in `post': Dependabot::Clients::Azure::Forbidden (Dependabot::Clients::Azure::Forbidden)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/clients/azure.rb:207:in `create_commit'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/pull_request_creator/azure.rb:74:in `create_commit'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/pull_request_creator/azure.rb:42:in `create'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.244.0/lib/dependabot/pull_request_creator.rb:236:in `create'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from bin/update_script.rb:833:in `block in <main>'
	from bin/update_script.rb:549:in `each'
	from bin/update_script.rb:549:in `<main>'
##[error]The process '/usr/bin/docker' failed with exit code 1
```
I'm not sure if this is related to the issues described above, but the same pipeline did work a few days ago.

**Comment by HardikTathod** [comment] 2024-02-21 08:54
@mburumaxwell Can you please help me with this issue
 running NuGet updater:
/opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/tmp/civilgeo/Presentation/_git/Presentation --solution-or-project /home/dependabot/dependabot-updater/tmp/civilgeo/Presentation/_git/Presentation/Sources/CivilGeo.Presentation.Ogr/CivilGeo.Presentation.Ogr.csproj --dependency Microsoft.SourceLink.AzureRepos.Git --new-version 8.0.0 --previous-version 1.1.1 --verbose
  No dotnet-tools.json files found.
Running for project [/home/dependabot/dependabot-updater/tmp/civilgeo/Presentation/_git/Presentation/Sources/CivilGeo.Presentation.Ogr/CivilGeo.Presentation.Ogr.csproj]
  Running for SDK-style project
dotnet build in GetAllPackageDependenciesAsync failed. STDOUT: MSBuild version 17.8.3+195e7f5a3 for .NET

**Comment by mburumaxwell** [comment] 2024-02-26 06:38
Type errors seems to no longer be present. Closing this now (1 weeks is over).

@HardikTathod try and run this with a private GitHub repository. If it works, then you need to add `dockerImageTag: '1.24'` to your task inputs on Azure DevOps. If there are no private packages/registries, then the issue is different. Either way, open a new issue for better tracking. If the issue shows up when using a GitHub repository, you will need to open an issue at https://github.com/dependabot/dependabot-core

**Closed by mburumaxwell** 2024-02-26 06:38 UTC

**Comment by NickGraham101** [comment] 2024-02-26 18:26
I’m still seeing a type error with the dependabot-updater-nuget image

I’ve checked the sha of the image being pulled down and it matches 1.26.4 (01bd877ea1aa15f8ce512b4dffe3b7bf4fc0ca740f724ab6c11a1377f04ccae3). 

```
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.245.0/lib/dependabot/pull_request_creator/branch_namer/solo_strategy.rb:39:in `new_branch_name'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.245.0/lib/dependabot/pull_request_creator/branch_namer.rb:68:in `new_branch_name'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.245.0/lib/dependabot/pull_request_creator.rb:306:in `azure_creator'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.245.0/lib/dependabot/pull_request_creator.rb:236:in `create'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11267/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from bin/update_script.rb:833:in `block in <main>'
	from bin/update_script.rb:549:in `each'
	from bin/update_script.rb:549:in `<main>'
```

Should I open a new issue?
