### ISSUE TITLE
 source sequence is illegal/malformed utf-8 (JSON::GeneratorError) when running dependabot in azure pipeline

### ISSUE THREAD

**Issue by wcunningham1966** [tinglesoftware/dependabot-azure-devops#872] opened 2023-11-09 17:01 UTC
Running our monthly update and this error came up out of the blue:

/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.236.0/lib/dependabot/clients/azure.rb:193:in `to_json': source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.236.0/lib/dependabot/clients/azure.rb:193:in `create_pull_request'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.236.0/lib/dependabot/pull_request_creator/azure.rb:84:in `create_pull_request'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.236.0/lib/dependabot/pull_request_creator/azure.rb:44:in `create'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.236.0/lib/dependabot/pull_request_creator.rb:118:in `create'
	from bin/update_script.rb:849:in `block in <main>'
	from bin/update_script.rb:565:in `each'
	from bin/update_script.rb:565:in `<main>'
##[error]The process '/usr/bin/docker' failed with exit code 1

It creates most of the pull requests and it worked fine last on 10/16/23.  We've made no changes on our repos in that time, so I'm guessing this is related to the  1.23.587 build of dependabot?

**Comment by wcunningham1966** [comment] 2023-11-09 19:30
Looks like this problem might be with @angular/cli    I removed that from my dependabot.yml and it ran fine.

**Comment by mburumaxwell** [comment] 2023-11-13 07:50
Duplicate of #730

**Closed by mburumaxwell** 2023-11-13 07:50 UTC
