### ISSUE TITLE
PR already exists or an error has occurred.

### ISSUE THREAD

**Issue by SeanFeldman** [tinglesoftware/dependabot-azure-devops#181] opened 2021-09-09 08:39 UTC
I'm getting the following error and not quite sure what is the problem:

```
Checking if Microsoft.Extensions.Configuration 3.1.18 needs updating
Requirements to unlock own
Updating Microsoft.Extensions.Configuration from 3.1.18 to 5.0.0
Submitting Microsoft.Extensions.Configuration pull request for creation. Failed! PR already exists or an error has occurred.
```

There's no PR, I've validated that.

The pipeline looks as the following:

```yaml
schedules:
  - cron: "0 4 * * 1"
    displayName: 'Weekly Run'
    always: true # run even when there are no code changes
    branches:
      include:
        - master
    batch: true
trigger: none # Disable CI trigger
pool:
  vmImage: 'ubuntu-latest'
steps:
  - task: dependabot@1
    displayName: 'Run Dependabot'
    inputs:
      packageManager: 'nuget'
      openPullRequestsLimit: 10
      versioningStrategy: 'auto'
      setAutoComplete: false
      azureDevOpsAccessToken: '$(System.AccessToken)'
```

Settings wise, `Contribute to pull requests` and `Create branch` are enabled:
![image](https://user-images.githubusercontent.com/1309622/132652873-4eb21ca7-61d8-4ab7-b6b9-9ed1e37b7562.png)

**Comment by SeanFeldman-Optimus** [comment] 2021-09-14 16:58
The issue was my experimental branch name. It was `dependabot` which is used as a prefix for all the PR/branches raised by the task. Make sure your branch name is not called `dependabot`, use Personal Access Token, and drink water! 😀

**Comment by JacekSmi** [comment] 2021-09-16 09:05
Hey, I got the same problem on my pipeline and want to put more light on that.
I've run dependabot with  EXCON_DEBUG=1 and looks like the problem is with the request body.
It's not trimmed at the end what cause 400 Bad request
After removing "dependabot" branch is working ok

>   }
  :host          => "dev.azure.com"
  :local_address => "172.17.0.2"
  :local_port    => 48496
  :path          => "/MyOrganization/MyProject/_apis/git/repositories/Myfeed/pushes"
  :port          => 443
  :reason_phrase => "Bad Request"
  :remote_ip     => "13.107.42.20"
  :status        => 400
  :status_line   => "HTTP/1.1 400 Bad Request\r\n"
excon.request
  **:body                => "{\"sourceRefName\":\"refs/heads/dependabot/nuget/develop/CSharpFunctionalExtensions-2.20.1\",\"targetRefName\":\"refs/heads/develop\",\"title\":\"Bump CSharpFunctionalExtensions from 2.15.3 to 2.20.1\",\"description\":\"Bumps [CSharpFunctionalExtensions](https://github.com/vkhorikov/CSharpFunctionalExtensions) from 2.15.3 to 2.20.1.\\n\\n#Release notes\\n\\n*Sourced from [CSharpFunctionalExtensions's releases](**
  :chunk_size          => 1048576
  :ciphers             => "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA:!DSS"
  :connect_timeout     => 5
  :debug_request       => true
  :debug_response      => true
  :headers             => {
    "Authorization" => "REDACTED"
    "Content-Type"  => "application/json"
    "Host"          => "dev.azure.com"
    "User-Agent"    => "dependabot-core/0.160.0 excon/0.85.0 ruby/2.7.1 (x86_64-linux-gnu) (+https://github.com/dependabot/dependabot-core)"
  }

**Comment by mburumaxwell** [comment] 2021-09-27 05:41
I will close this issue. If there are more either reopen or create a more specific issue.

**Closed by mburumaxwell** 2021-09-27 05:41 UTC
