### ISSUE TITLE
dependabot.yml ignored versions are still updated

### ISSUE THREAD

**Issue by DevDavido** [tinglesoftware/dependabot-azure-devops#476] opened 2023-01-18 19:04 UTC
Hello,
ignored dependencies in the dependbot.yml are completely ignored and PRs are still created.
Azure Pipeline:
```yml
# ...
steps:
  - task: dependabot@1
    displayName: 'Scheduled Dependabot Update'
    inputs:
      dockerImageTag: 0.14.0
      azureDevOpsAccessToken: 'THE_DEPENDABOT_ADO_PAT'
      gitHubConnection: 'THE_DEPENDABOT_GITHUB_SERVICE_CONNECTION'
      extraEnvironmentVariables: DEPENDABOT_AUTHOR_NAME=dependabot; DEPENDABOT_AUTHOR_EMAIL=dependabot@abc.com
```

dependabot.yml with ignored `ch.qos.logback:logback-classic`, but PR with minor update for it is still created:
```yml
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "versions"
    target-branch: "dependabot/develop"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "dependabot"
    ignore:
      # Ignore all major and patch updates for now
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-patch" ]
      # Ignore list
      - dependency-name: "ch.qos.logback:logback-classic"
```
Would it be also possible to print the ignored versions to the output?

Edit:
Changing the `update-types` to `[ "version-update:semver-major", "version-update:semver-minor" ]` seems to be ignored completely too. Minor update PR gets still created.

Also tried to use ENV `DEPENDABOT_IGNORE_CONDITIONS` to set the ignore conditions like this, also same result as before:
`extraEnvironmentVariables: DEPENDABOT_AUTHOR_NAME=dependabot; DEPENDABOT_AUTHOR_EMAIL=dependabot@abc.com; DEPENDABOT_IGNORE_CONDITIONS='[{"dependency-name":"ch.qos.logback:logback-classic"}]'`

**Comment by mburumaxwell** [comment] 2023-01-18 20:45
Could you offer a public repro for this?

**Comment by DevDavido** [comment] 2023-01-18 20:54
Unfortunately not, it's a private corporate repository where we plan to potentially integrate this extension.
Would it help to provide the build.gradle?
```groovy
plugins {
    id 'java-platform'
}

group = 'com.ab.cd'

dependencies {
    constraints {
        api "ch.qos.logback:logback-classic:1.4.5"
        // [...]
    }
}
```

**Comment by mburumaxwell** [comment] 2023-01-18 20:57
A reproduction of this means a representation of what you have without exposing details. Such as https://dev.azure.com/tingle/dependabot/_git/repro-366 plus an accompanying pipeline.

It could even be your own personal account.

**Comment by mburumaxwell** [comment] 2023-01-19 16:11
Related to https://github.com/dependabot/dependabot-core/issues/6481?

**Comment by DevDavido** [comment] 2023-01-19 19:51
> A reproduction of this means a representation of what you have without exposing details.

It might take some time until I could maybe provide a representation of the described issue.
It seems that Dependabot for ADO is not passing the ignore node to Dependabot itself? Is that possible?

> Related to [dependabot/dependabot-core#6481](https://github.com/dependabot/dependabot-core/issues/6481)?

It's not related to issue 6481.

**Comment by mburumaxwell** [comment] 2023-01-19 22:43
> It's not related to issue 6481.

You may not be the creator of the issue but it sure does look similar.

Anyway, let's talk when you have a reproduction because the config file have posted has a couple of issues like the directory not starting with a forward slash, the target branch value is likely problematic etc. I would also need to see the actual version being accepted/rejected.

**Comment by DevDavido** [comment] 2023-01-22 17:24
I setup a public repository with ADO for reproduction:
https://dev.azure.com/devdavido/dependabot/_git/dependabot

However, due to changes for public projects @ ADO, I cannot run the pipeline for that public repositories without a legitimate open source project anymore ("[we will grant public project concurrency only to validated open source projects](https://aka.ms/azpipelines-parallelism-request)") with my newly created account (see screenshots) and MS hosted agents:
<img width="524" alt="" src="https://user-images.githubusercontent.com/997605/213930172-676aba5b-e5d4-4048-afcc-3909eac97497.png">


With the provided repo, would it be possible to import and reproduce it?

**Comment by mburumaxwell** [comment] 2023-01-23 02:43
You do not need to really alter the concurrency since you're not running multiple pipelines at once. However, you may need an agent to run jobs. That said, the repository provides enough information to work with. I cloned it, simplified the pipeline and did a run to see if I can reproduce the issue.

Pipeline Run: https://dev.azure.com/tingle/dependabot/_build/results?buildId=54710

I notice the following:
1. `ch.qos.logback:logback-classic` version `1.0.0` does not get updated ([log line 279](https://dev.azure.com/tingle/dependabot/_build/results?buildId=54710&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1f93c1a3-255b-505a-53c9-c382114aabf5&l=279)). This is the expected behaviour as per [the configuration file, line 14](https://dev.azure.com/tingle/dependabot/_git/repro-476?path=/.github/dependabot.yml&version=GBmain&line=14&lineEnd=14&lineStartColumn=1&lineEndColumn=58&lineStyle=plain&_a=contents)
2. `ch.qos.logback:logback-core` version `1.0.0` gets updated to the next latest minor version `1.4.5` ([log line 286](https://dev.azure.com/tingle/dependabot/_build/results?buildId=54710&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1f93c1a3-255b-505a-53c9-c382114aabf5&l=286). This is the expected behaviour since the default configured behaviour is to ignore major and patch version as per [the configuration file, lines 11&12](https://dev.azure.com/tingle/dependabot/_git/repro-476?path=/.github/dependabot.yml&version=GBmain&line=11&lineEnd=13&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)

It would appear to be functioning as expected.

**Comment by stanrogo** [comment] 2023-01-26 11:35
Hi there, I am also having the same issue that the .yml ignored versions are being updated.

You mentioned that the ruby script picks up the ignored versions, but from what I have found in the code, this doesn't seem to be the case. Specifically in the extension file https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/extension/task/index.ts where the variables from the configuration are parsed, the `ignore` property doesn't seem to be present. Yes, the ruby script has `DEPENDABOT_IGNORE_CONDITIONS` as an environment variable, but this does not seem to be set anywhere. Further, in https://github.com/tinglesoftware/dependabot-azure-devops/pull/401 the variable was changed to be only picked up when not using a configuration file.

I would expect `dockerRunner.arg(["-e", `DEPENDABOT_IGNORE_CONDITIONS=${ignore}`]);` to still be present, which would fix my issues entirely. Is there a reason why this was removed? Right now we are in the tricky place of having two dependabot.yml files because of this, one which is dynamically generated and parsed by the azure devops extension, and the other which is statically committed to the repository and read from the dependabot docker container which then does pick up the ignore property. This isn't ideal.

**Comment by mburumaxwell** [comment] 2023-01-26 12:47
@stanrogo

1. Did you look at the sample I provided in the previous comment?
2. How does the sample I provided above differ from yours?
3. Where's the public repo to prove that this extension does not function in your ideal situation?
4. Where are the logs?

**Comment by mburumaxwell** [comment] 2023-02-01 12:16
Closing this as it cannot be reproduced. Please reopen with a repro.

**Closed by mburumaxwell** 2023-02-01 12:16 UTC
