### ISSUE TITLE
Dependabot abandoning our own PRs

### ISSUE THREAD

**Issue by MEmanuelsson** [tinglesoftware/dependabot-azure-devops#471] opened 2023-01-16 13:10 UTC
We're running dependabot once a week to keep our Nuget-packages (primarily) up to date. "Bump-PRs" are created as expected but since the functionality to also abandon outdated PRs was introduced we've also experienced that our own PRs are being abandonded as well. 

What criterias is this functionality looking at to decide if a PR should be abandonded or not? We're running a monorepo as well, if this has something to do with the issue reported here: https://github.com/tinglesoftware/dependabot-azure-devops/issues/451? 

For now I will look into disabling this functionality to avoid problems like this but I just wanted to report this issue to you.

**Comment by mburumaxwell** [comment] 2023-01-16 13:49
Duplicate of #451

**Closed** 2023-01-16 13:57 UTC

**Comment by mburumaxwell** [comment] 2023-01-24 03:24
I really hope this is now fixed in the right way in #482
