### ISSUE TITLE
Private NPM registry package URL incorrect causing a 404

### ISSUE THREAD

**Issue by SomniumDigital** [tinglesoftware/dependabot-azure-devops#364] opened 2022-10-05 16:09 UTC
I am trying to check for updates to packages within a scope stored in a private Azure Devops Artifacts registry. When Dependabot runs it seems to auth OK and correctly detect that there is a newer version of the package available, it then tries to retrieve the package cycling through several URL's which all 404 finally resulting in the package not getting updated and Dependabot returning a `Updating @my-scope/my-package is not allowed` message.

Pipeline task:

```
- task: dependabot@1
  displayName: "Check dependancies"
  inputs:
    useConfigFile: true
    extraEnvironmentVariables: 'DEPENDABOT_EXTRA_CREDENTIALS=[{"type":"npm_registry","token":"<my-user>:$(System.AccessToken)","registry":"pkgs.dev.azure.com/<my-org>/<my-project1>/_packaging/<my-feed1>/npm/registry/"}, {"type":"npm_registry","token":"<my-user>:$(System.AccessToken)","registry":"pkgs.dev.azure.com/<my-org>/<my-project2>/_packaging/<my-feed3>/npm/registry/"}, {"type":"npm_registry","token":"<my-user>:$(System.AccessToken)","registry":"pkgs.dev.azure.com/<my-org>/<my-project3>/_packaging/<my-feed2>/npm/registry/"}]'
```
Dependabot yaml:

```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/redacted/core"
    target-branch: "master"
    allow:
      - dependency-name: "@my-scope/*"
    schedule:
      interval: "daily"
```

.npmrc:
```
# Has an upstream to https://pkgs.dev.azure.com/<my-org>/<my-project-1>/_packaging/<my-feed1>/npm/registry/
@my-scope:registry=https://pkgs.dev.azure.com/<my-org>/<my-project3>/_packaging/<my-feed2>/npm/registry/
always-auth=true

@my-scope=https://pkgs.dev.azure.com/<my-org>/<my-project2>/_packaging/<my-feed3>/npm/registry/
always-auth=true

@my-scope=https://pkgs.dev.azure.com/<my-org>/<my-project1>/_packaging/<my-feed1>/npm/registry/
always-auth=true
```

The URL's it cycles through are below (I believe these are set in Dependabot core):
`<my-org>/<my-project-1>/_packaging/<my-feed1>/npm/registry/@my-scope/my-package/6.3.0`
`<my-org>/<my-project-1>/_packaging/<my-feed1>/npm/registry/@my-scope%2Fmy-package/6.3.0`
`<my-org>/<my-project-1>/_packaging/<my-feed1>/npm/registry/@my-scope%2Fmy-package/latest`

I've tried hitting all of these URL's on Postman to no success, however when looking up the package (without the version number/latest appended) I am able to successfully see a response containing details about the package.

N.B. I am using Yarn as the package manager, a package.json, yarn.lock and the .npmrc file all live in the directory set in the `dependabot.yml`

**Comment by mburumaxwell** [comment] 2022-11-07 12:56
@SomniumDigital I am unable to figure out what is happening here because we have updates for npm using a private feed/registry and it works. Much more information may be required to solve this. I hope to get time to look through at any possible missing configurations.

**Comment by SomniumDigital** [comment] 2022-11-14 09:55
Hi @mburumaxwell, thanks for taking the time to investigate. Is there any extra info in particular that may be of help?

**Comment by mburumaxwell** [comment] 2022-12-05 09:06
@SomniumDigital ,

In the more recent releases, support for the `registries` node was added. Could you try with this to see if resolved?
Also, this could be related to authentication issues around project-scoped feeds. Unfortunately, I am not very conversant with them. Maybe you could try with organization-scope feeds?

Your configuration file at `.github/dependabot.yml`:

```yaml
version: 2
updates:
- package-ecosystem: "npm"
  directory: "/frontend"
  target-branch: "master"
registries:
  reg1:
    type: npm-registry
    url: 'https://pkgs.dev.azure.com/<my-org>/<my-project1>/_packaging/<my-feed1>/npm/registry/'
    token: '<my-user>:${{PKG_TOKEN}}'
  reg2:
    type: npm-registry
    url: 'https://pkgs.dev.azure.com/<my-org>/<my-project2>/_packaging/<my-feed3>/npm/registry/'
    token: '<my-user>:${{PKG_TOKEN}}'
  reg3:
    type: npm-registry
    url: 'https://pkgs.dev.azure.com/<my-org>/<my-project3>/_packaging/<my-feed2>/npm/registry/'
    token: '<my-user>:${{PKG_TOKEN}}'
```

Your pipeline:

```yaml
variables:
  PKG_TOKEN: '$(System.AccessToken)'

steps:
- task: dependabot@1
  displayName: "Check dependencies"
  inputs:
    useConfigFile: true
```

**Comment by mburumaxwell** [comment] 2023-02-07 14:24
@SomniumDigital I see a number of 404 requests too. Now even with the new `registries` node.
My suspicion is that Azure Artifacts is not 100% compliant to registry.npmjs.org or the standards for an NPM registry.

Since dependabot does not throw an exception due to these 404 responses it would appear that they are not crucial and possible a known behaviour. These 404 scenarios is similar to when a package is not present on a particular feed such as trying to find a private package in a public feed.

This does not concern me much because:
1. Pull requests for updates are still created despite the 404 responses on our end.
2. This particular issue would be affecting many more users beyond this extension's usage and would possible have been reported in the core repo.
3. Changes to such functionality would need to be done in the core repo.

If the bother you as much, perhaps you could raise an issue with the Azure team?

For now, I will close the issue.

**Closed by mburumaxwell** 2023-02-07 14:24 UTC
Labels: question

**Comment by DavidDeSloovere** [comment] 2023-09-08 12:34
I can confirm tht updating packages against a private npm registry in AzDO works eventhough you see 404 errors.
